package com.myspace.mostafatestingcomplexobject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label(value = "address")
	private java.lang.String address;
	@org.kie.api.definition.type.Label(value = "phone")
	private java.lang.Integer phone;

	public customer() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.Integer getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.Integer phone) {
		this.phone = phone;
	}

	public customer(java.lang.String name, java.lang.Integer age,
			java.lang.String address, java.lang.Integer phone) {
		this.name = name;
		this.age = age;
		this.address = address;
		this.phone = phone;
	}

}