package com.myspace.mostafatestingcomplexobject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class customers implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "customer")
	private java.util.List<com.myspace.mostafatestingcomplexobject.customer> customer;

	public customers() {
	}

	public java.util.List<com.myspace.mostafatestingcomplexobject.customer> getCustomer() {
		return this.customer;
	}

	public void setCustomer(
			java.util.List<com.myspace.mostafatestingcomplexobject.customer> customer) {
		this.customer = customer;
	}

	public customers(
			java.util.List<com.myspace.mostafatestingcomplexobject.customer> customer) {
		this.customer = customer;
	}

}